// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VvsIms.Infrastructure.Persistence;

#nullable disable

namespace VvsIms.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(VvsImsDbContext))]
    partial class VvsImsDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("VvsIms.Domain.Entities.AuditLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("AfterPayload")
                        .HasColumnType("longtext");

                    b.Property<string>("BeforePayload")
                        .HasColumnType("longtext");

                    b.Property<string>("ClientIp")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("CorrelationId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasDefaultValueSql("UTC_TIMESTAMP()");

                    b.Property<int?>("DurationMs")
                        .HasColumnType("int");

                    b.Property<string>("Endpoint")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("EntityKey")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("EntityType")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("ErrorDetails")
                        .HasColumnType("longtext");

                    b.Property<string>("HttpMethod")
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.Property<string>("Module")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("RequestPayload")
                        .HasColumnType("longtext");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.Property<string>("UserEmail")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("UserId")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("CorrelationId");

                    b.ToTable("audit_log", (string)null);
                });

            modelBuilder.Entity("VvsIms.Domain.Entities.ChannelMapping", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ChannelName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("ChannelSKU")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasDefaultValueSql("UTC_TIMESTAMP()");

                    b.Property<string>("ShopSKU")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("SystemSKU")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("SystemSKU", "ChannelName");

                    b.ToTable("channel_mapping", (string)null);
                });

            modelBuilder.Entity("VvsIms.Domain.Entities.IdempotencyKey", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("ProcessedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Result")
                        .HasColumnType("longtext");

                    b.Property<bool>("Success")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.ToTable("idempotency_key");
                });

            modelBuilder.Entity("VvsIms.Domain.Entities.Inventory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasDefaultValueSql("UTC_TIMESTAMP()");

                    b.Property<int>("Platform")
                        .HasColumnType("int");

                    b.Property<DateTime?>("PlatformDiscountEndDate")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("PlatformDiscountStartDate")
                        .HasColumnType("datetime(6)");

                    b.Property<short?>("PlatformQuantity")
                        .HasColumnType("smallint");

                    b.Property<string>("PlatformSkuTitle")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<bool?>("PlatformWinningOffer")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("Winning")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(false);

                    b.HasKey("Id");

                    b.ToTable("inventory", (string)null);
                });

            modelBuilder.Entity("VvsIms.Domain.Entities.InventoryEvent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Channel")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ChannelEventId")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("Delta")
                        .HasColumnType("int");

                    b.Property<int>("InventoryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("OccurredAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("SystemSKU")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.ToTable("inventory_event");
                });

            modelBuilder.Entity("VvsIms.Domain.Entities.InventoryItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Color")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<decimal?>("Cost")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasDefaultValueSql("UTC_TIMESTAMP()");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("DateShip")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Grade")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Imei")
                        .HasMaxLength(17)
                        .HasColumnType("varchar(17)");

                    b.Property<int>("InventoryId")
                        .HasColumnType("int");

                    b.Property<string>("InvoiceNo")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Model")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Order")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Rma")
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.Property<string>("Sku")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Storage")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Vendor")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("InventoryId");

                    b.ToTable("inventory_item", (string)null);
                });

            modelBuilder.Entity("VvsIms.Domain.Entities.Notification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("IsRead")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("RelatedEntity")
                        .HasColumnType("longtext");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.ToTable("notification");
                });

            modelBuilder.Entity("VvsIms.Domain.Entities.Outgoing", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("Date")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Imei")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("OrderNo")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("OrderStatus")
                        .HasColumnType("longtext");

                    b.Property<string>("ProductTitle")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.ToTable("outgoing");
                });

            modelBuilder.Entity("VvsIms.Domain.Entities.Pending", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("DateAdded")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Imei")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("OrderNo")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ProductTitle")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.ToTable("pending");
                });

            modelBuilder.Entity("VvsIms.Domain.Entities.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasDefaultValueSql("UTC_TIMESTAMP()");

                    b.Property<string>("Imei")
                        .IsRequired()
                        .HasMaxLength(17)
                        .HasColumnType("varchar(17)");

                    b.Property<string>("InvoiceNumber")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<bool?>("PhoneCheck")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(false);

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Vendor")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.ToTable("product", (string)null);
                });

            modelBuilder.Entity("VvsIms.Domain.Entities.ProductSku", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasDefaultValueSql("UTC_TIMESTAMP()");

                    b.Property<int>("Grade")
                        .HasColumnType("int");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Sku")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Storage")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("Sku")
                        .IsUnique();

                    b.ToTable("product_sku", (string)null);
                });

            modelBuilder.Entity("VvsIms.Domain.Entities.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("RoleDescription")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("RolePermissions")
                        .HasMaxLength(2000)
                        .HasColumnType("varchar(2000)");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("RoleName")
                        .IsUnique()
                        .HasDatabaseName("ix_role_role_name_unique");

                    b.ToTable("role", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAtUtc = new DateTime(2026, 5, 19, 3, 28, 20, 346, DateTimeKind.Utc).AddTicks(7378),
                            CreatedBy = "System",
                            RoleDescription = "Full system administrator with all permissions.",
                            RoleName = "Admin",
                            RolePermissions = "stock:read,stock:write,inventory:read,inventory:write,product:read,product:write,user:read,user:write,report:read,report:write,settings:read,settings:write"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAtUtc = new DateTime(2026, 5, 19, 3, 28, 20, 346, DateTimeKind.Utc).AddTicks(7382),
                            CreatedBy = "System",
                            RoleDescription = "Standard user with read and limited write permissions.",
                            RoleName = "User",
                            RolePermissions = "stock:read,inventory:read,product:read,report:read"
                        });
                });

            modelBuilder.Entity("VvsIms.Domain.Entities.Stock", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasDefaultValueSql("UTC_TIMESTAMP()");

                    b.Property<DateTime?>("DateAdded")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("DateSold")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Imei")
                        .IsRequired()
                        .HasMaxLength(17)
                        .HasColumnType("varchar(17)");

                    b.Property<string>("InvoiceNumber")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<bool>("IsManualImei")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(false);

                    b.Property<bool>("IsShipped")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(false);

                    b.Property<DateTime?>("OrderLandingDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("OrderNo")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("OrderStatus")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<bool?>("PhoneCheck")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(false);

                    b.Property<bool>("Rma")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(false);

                    b.Property<DateTime?>("ShippedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Vendor")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Imei")
                        .IsUnique();

                    b.ToTable("stock", (string)null);
                });

            modelBuilder.Entity("VvsIms.Domain.Entities.StockReturn", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Channel")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Imei")
                        .HasColumnType("longtext");

                    b.Property<int?>("Quantity")
                        .HasColumnType("int");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("ReturnDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("ReturnOrderNo")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Sku")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("StockId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("StockId");

                    b.ToTable("stock_return");
                });

            modelBuilder.Entity("VvsIms.Domain.Entities.StockSyncLock", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("LastSyncAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.ToTable("stock_sync_lock");
                });

            modelBuilder.Entity("VvsIms.Domain.Entities.SystemSkuStockSnapshot", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("LastKnownAvailable")
                        .HasColumnType("int");

                    b.Property<DateTime>("LastSyncUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("SystemSKU")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.ToTable("system_sku_stock_snapshot");
                });

            modelBuilder.Entity("VvsIms.Domain.Entities.ThreadMessage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("MessageDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("OrderId")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("SenderName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ThreadId")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.ToTable("thread_message");
                });

            modelBuilder.Entity("VvsIms.Domain.Entities.ThreadResponse", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("OrderId")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("RespondedBy")
                        .HasColumnType("longtext");

                    b.Property<string>("Response")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("ResponseDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Tag")
                        .HasColumnType("longtext");

                    b.Property<string>("ThreadId")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ToType")
                        .HasColumnType("longtext");

                    b.Property<string>("TopicType")
                        .HasColumnType("longtext");

                    b.Property<string>("TopicValue")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.ToTable("thread_response");
                });

            modelBuilder.Entity("VvsIms.Domain.Entities.ThreadStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasDefaultValueSql("UTC_TIMESTAMP()");

                    b.Property<string>("OrderId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("ThreadId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("ThreadId")
                        .IsUnique();

                    b.ToTable("thread_status", (string)null);
                });

            modelBuilder.Entity("VvsIms.Domain.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(true);

                    b.Property<string>("Password")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<byte[]>("PasswordHash")
                        .HasColumnType("longblob");

                    b.Property<byte[]>("PasswordSalt")
                        .HasColumnType("longblob");

                    b.Property<string>("RefreshToken")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<DateTime?>("RefreshTokenExpiryTime")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("UserEmail")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("UserFirstName")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("UserLastName")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("UserPhone")
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.Property<string>("UserPreferredName")
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.HasIndex("UserEmail")
                        .IsUnique()
                        .HasDatabaseName("ix_user_user_email_unique");

                    b.HasIndex("UserName")
                        .IsUnique()
                        .HasDatabaseName("ix_user_user_name_unique");

                    b.ToTable("user", (string)null);
                });

            modelBuilder.Entity("VvsIms.Domain.Entities.Inventory", b =>
                {
                    b.OwnsOne("VvsIms.Domain.ValueObjects.Money", "AdjustmentPrice", b1 =>
                        {
                            b1.Property<int>("InventoryId")
                                .HasColumnType("int");

                            b1.Property<decimal>("Amount")
                                .HasPrecision(10, 2)
                                .HasColumnType("decimal(10,2)")
                                .HasColumnName("adjustment_price");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .ValueGeneratedOnAdd()
                                .HasMaxLength(3)
                                .HasColumnType("varchar(3)")
                                .HasDefaultValue("CAD")
                                .HasColumnName("adjustment_price_currency");

                            b1.HasKey("InventoryId");

                            b1.ToTable("inventory._adjustment_price#_money");

                            b1.WithOwner()
                                .HasForeignKey("InventoryId");
                        });

                    b.OwnsOne("VvsIms.Domain.ValueObjects.BaseProperties", "BaseProperties", b1 =>
                        {
                            b1.Property<int>("InventoryId")
                                .HasColumnType("int");

                            b1.Property<int>("BuyingPlatform")
                                .HasColumnType("int")
                                .HasColumnName("buying_platform");

                            b1.Property<string>("Color")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("varchar(50)")
                                .HasColumnName("color");

                            b1.Property<int>("Grade")
                                .HasColumnType("int")
                                .HasColumnName("grade");

                            b1.Property<string>("Model")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("varchar(100)")
                                .HasColumnName("model");

                            b1.Property<string>("Sku")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("varchar(50)")
                                .HasColumnName("sku");

                            b1.Property<string>("Storage")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("varchar(50)")
                                .HasColumnName("storage");

                            b1.HasKey("InventoryId");

                            b1.ToTable("inventory._base_properties#_base_properties");

                            b1.WithOwner()
                                .HasForeignKey("InventoryId");

                            b1.OwnsOne("VvsIms.Domain.ValueObjects.Money", "Cost", b2 =>
                                {
                                    b2.Property<int>("BasePropertiesInventoryId")
                                        .HasColumnType("int");

                                    b2.Property<decimal>("Amount")
                                        .HasPrecision(10, 2)
                                        .HasColumnType("decimal(10,2)")
                                        .HasColumnName("cost");

                                    b2.Property<string>("Currency")
                                        .IsRequired()
                                        .ValueGeneratedOnAdd()
                                        .HasMaxLength(3)
                                        .HasColumnType("varchar(3)")
                                        .HasDefaultValue("CAD")
                                        .HasColumnName("cost_currency");

                                    b2.HasKey("BasePropertiesInventoryId");

                                    b2.ToTable("inventory._base_properties#_base_properties._cost#_money");

                                    b2.WithOwner()
                                        .HasForeignKey("BasePropertiesInventoryId");
                                });

                            b1.Navigation("Cost")
                                .IsRequired();
                        });

                    b.OwnsOne("VvsIms.Domain.ValueObjects.Money", "Bought", b1 =>
                        {
                            b1.Property<int>("InventoryId")
                                .HasColumnType("int");

                            b1.Property<decimal>("Amount")
                                .HasPrecision(10, 2)
                                .HasColumnType("decimal(10,2)")
                                .HasColumnName("bought");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .ValueGeneratedOnAdd()
                                .HasMaxLength(3)
                                .HasColumnType("varchar(3)")
                                .HasDefaultValue("CAD")
                                .HasColumnName("bought_currency");

                            b1.HasKey("InventoryId");

                            b1.ToTable("inventory._bought#_money");

                            b1.WithOwner()
                                .HasForeignKey("InventoryId");
                        });

                    b.OwnsOne("VvsIms.Domain.ValueObjects.Money", "PlatformDifference", b1 =>
                        {
                            b1.Property<int>("InventoryId")
                                .HasColumnType("int");

                            b1.Property<decimal>("Amount")
                                .HasPrecision(10, 2)
                                .HasColumnType("decimal(10,2)")
                                .HasColumnName("platform_difference");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .ValueGeneratedOnAdd()
                                .HasMaxLength(3)
                                .HasColumnType("varchar(3)")
                                .HasDefaultValue("CAD")
                                .HasColumnName("platform_difference_currency");

                            b1.HasKey("InventoryId");

                            b1.ToTable("inventory._platform_difference#_money");

                            b1.WithOwner()
                                .HasForeignKey("InventoryId");
                        });

                    b.OwnsOne("VvsIms.Domain.ValueObjects.Money", "PlatformDiscountPrice", b1 =>
                        {
                            b1.Property<int>("InventoryId")
                                .HasColumnType("int");

                            b1.Property<decimal>("Amount")
                                .HasPrecision(10, 2)
                                .HasColumnType("decimal(10,2)")
                                .HasColumnName("platform_discount_price");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .ValueGeneratedOnAdd()
                                .HasMaxLength(3)
                                .HasColumnType("varchar(3)")
                                .HasDefaultValue("CAD")
                                .HasColumnName("platform_discount_price_currency");

                            b1.HasKey("InventoryId");

                            b1.ToTable("inventory._platform_discount_price#_money");

                            b1.WithOwner()
                                .HasForeignKey("InventoryId");
                        });

                    b.OwnsOne("VvsIms.Domain.ValueObjects.Money", "PlatformPrice", b1 =>
                        {
                            b1.Property<int>("InventoryId")
                                .HasColumnType("int");

                            b1.Property<decimal>("Amount")
                                .HasPrecision(10, 2)
                                .HasColumnType("decimal(10,2)")
                                .HasColumnName("platform_price");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .ValueGeneratedOnAdd()
                                .HasMaxLength(3)
                                .HasColumnType("varchar(3)")
                                .HasDefaultValue("CAD")
                                .HasColumnName("platform_price_currency");

                            b1.HasKey("InventoryId");

                            b1.ToTable("inventory._platform_price#_money");

                            b1.WithOwner()
                                .HasForeignKey("InventoryId");
                        });

                    b.OwnsOne("VvsIms.Domain.ValueObjects.Money", "PlatformWinnerPrice", b1 =>
                        {
                            b1.Property<int>("InventoryId")
                                .HasColumnType("int");

                            b1.Property<decimal>("Amount")
                                .HasPrecision(10, 2)
                                .HasColumnType("decimal(10,2)")
                                .HasColumnName("platform_winner_price");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .ValueGeneratedOnAdd()
                                .HasMaxLength(3)
                                .HasColumnType("varchar(3)")
                                .HasDefaultValue("CAD")
                                .HasColumnName("platform_winner_price_currency");

                            b1.HasKey("InventoryId");

                            b1.ToTable("inventory._platform_winner_price#_money");

                            b1.WithOwner()
                                .HasForeignKey("InventoryId");
                        });

                    b.OwnsOne("VvsIms.Domain.ValueObjects.Money", "PlatformWinnerShippingPrice", b1 =>
                        {
                            b1.Property<int>("InventoryId")
                                .HasColumnType("int");

                            b1.Property<decimal>("Amount")
                                .HasPrecision(10, 2)
                                .HasColumnType("decimal(10,2)")
                                .HasColumnName("platform_winner_shipping_price");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .ValueGeneratedOnAdd()
                                .HasMaxLength(3)
                                .HasColumnType("varchar(3)")
                                .HasDefaultValue("CAD")
                                .HasColumnName("platform_winner_shipping_price_currency");

                            b1.HasKey("InventoryId");

                            b1.ToTable("inventory._platform_winner_shipping_price#_money");

                            b1.WithOwner()
                                .HasForeignKey("InventoryId");
                        });

                    b.OwnsOne("VvsIms.Domain.ValueObjects.Money", "ProductWinningPrice", b1 =>
                        {
                            b1.Property<int>("InventoryId")
                                .HasColumnType("int");

                            b1.Property<decimal>("Amount")
                                .HasPrecision(10, 2)
                                .HasColumnType("decimal(10,2)")
                                .HasColumnName("product_winning_price");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .ValueGeneratedOnAdd()
                                .HasMaxLength(3)
                                .HasColumnType("varchar(3)")
                                .HasDefaultValue("CAD")
                                .HasColumnName("product_winning_price_currency");

                            b1.HasKey("InventoryId");

                            b1.ToTable("inventory._product_winning_price#_money");

                            b1.WithOwner()
                                .HasForeignKey("InventoryId");
                        });

                    b.OwnsOne("VvsIms.Domain.ValueObjects.Money", "SellingPrice", b1 =>
                        {
                            b1.Property<int>("InventoryId")
                                .HasColumnType("int");

                            b1.Property<decimal>("Amount")
                                .HasPrecision(10, 2)
                                .HasColumnType("decimal(10,2)")
                                .HasColumnName("selling_price");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .ValueGeneratedOnAdd()
                                .HasMaxLength(3)
                                .HasColumnType("varchar(3)")
                                .HasDefaultValue("CAD")
                                .HasColumnName("selling_price_currency");

                            b1.HasKey("InventoryId");

                            b1.ToTable("inventory._selling_price#_money");

                            b1.WithOwner()
                                .HasForeignKey("InventoryId");
                        });

                    b.Navigation("AdjustmentPrice");

                    b.Navigation("BaseProperties")
                        .IsRequired();

                    b.Navigation("Bought");

                    b.Navigation("PlatformDifference");

                    b.Navigation("PlatformDiscountPrice");

                    b.Navigation("PlatformPrice");

                    b.Navigation("PlatformWinnerPrice");

                    b.Navigation("PlatformWinnerShippingPrice");

                    b.Navigation("ProductWinningPrice");

                    b.Navigation("SellingPrice");
                });

            modelBuilder.Entity("VvsIms.Domain.Entities.InventoryItem", b =>
                {
                    b.HasOne("VvsIms.Domain.Entities.Inventory", "Inventory")
                        .WithMany("InventoryItems")
                        .HasForeignKey("InventoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Inventory");
                });

            modelBuilder.Entity("VvsIms.Domain.Entities.Product", b =>
                {
                    b.OwnsOne("VvsIms.Domain.ValueObjects.BaseProperties", "BaseProperties", b1 =>
                        {
                            b1.Property<int>("ProductId")
                                .HasColumnType("int");

                            b1.Property<int>("BuyingPlatform")
                                .HasColumnType("int")
                                .HasColumnName("buying_platform");

                            b1.Property<string>("Color")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("varchar(50)")
                                .HasColumnName("color");

                            b1.Property<int>("Grade")
                                .HasColumnType("int")
                                .HasColumnName("grade");

                            b1.Property<string>("Model")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("varchar(100)")
                                .HasColumnName("model");

                            b1.Property<string>("Sku")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("varchar(50)")
                                .HasColumnName("sku");

                            b1.Property<string>("Storage")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("varchar(50)")
                                .HasColumnName("storage");

                            b1.HasKey("ProductId");

                            b1.ToTable("product._base_properties#_base_properties");

                            b1.WithOwner()
                                .HasForeignKey("ProductId");

                            b1.OwnsOne("VvsIms.Domain.ValueObjects.Money", "Cost", b2 =>
                                {
                                    b2.Property<int>("BasePropertiesProductId")
                                        .HasColumnType("int");

                                    b2.Property<decimal>("Amount")
                                        .HasPrecision(10, 2)
                                        .HasColumnType("decimal(10,2)")
                                        .HasColumnName("cost");

                                    b2.Property<string>("Currency")
                                        .IsRequired()
                                        .ValueGeneratedOnAdd()
                                        .HasMaxLength(3)
                                        .HasColumnType("varchar(3)")
                                        .HasDefaultValue("CAD")
                                        .HasColumnName("cost_currency");

                                    b2.HasKey("BasePropertiesProductId");

                                    b2.ToTable("product._base_properties#_base_properties._cost#_money");

                                    b2.WithOwner()
                                        .HasForeignKey("BasePropertiesProductId");
                                });

                            b1.Navigation("Cost")
                                .IsRequired();
                        });

                    b.Navigation("BaseProperties")
                        .IsRequired();
                });

            modelBuilder.Entity("VvsIms.Domain.Entities.Stock", b =>
                {
                    b.OwnsOne("VvsIms.Domain.ValueObjects.BaseProperties", "BaseProperties", b1 =>
                        {
                            b1.Property<int>("StockId")
                                .HasColumnType("int");

                            b1.Property<int>("BuyingPlatform")
                                .HasColumnType("int")
                                .HasColumnName("buying_platform");

                            b1.Property<string>("Color")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("varchar(50)")
                                .HasColumnName("color");

                            b1.Property<int>("Grade")
                                .HasColumnType("int")
                                .HasColumnName("grade");

                            b1.Property<string>("Model")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("varchar(100)")
                                .HasColumnName("model");

                            b1.Property<string>("Sku")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("varchar(50)")
                                .HasColumnName("sku");

                            b1.Property<string>("Storage")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("varchar(50)")
                                .HasColumnName("storage");

                            b1.HasKey("StockId");

                            b1.ToTable("stock._base_properties#_base_properties");

                            b1.WithOwner()
                                .HasForeignKey("StockId");

                            b1.OwnsOne("VvsIms.Domain.ValueObjects.Money", "Cost", b2 =>
                                {
                                    b2.Property<int>("BasePropertiesStockId")
                                        .HasColumnType("int");

                                    b2.Property<decimal>("Amount")
                                        .HasPrecision(10, 2)
                                        .HasColumnType("decimal(10,2)")
                                        .HasColumnName("cost");

                                    b2.Property<string>("Currency")
                                        .IsRequired()
                                        .ValueGeneratedOnAdd()
                                        .HasMaxLength(3)
                                        .HasColumnType("varchar(3)")
                                        .HasDefaultValue("CAD")
                                        .HasColumnName("cost_currency");

                                    b2.HasKey("BasePropertiesStockId");

                                    b2.ToTable("stock._base_properties#_base_properties._cost#_money");

                                    b2.WithOwner()
                                        .HasForeignKey("BasePropertiesStockId");
                                });

                            b1.Navigation("Cost")
                                .IsRequired();
                        });

                    b.Navigation("BaseProperties")
                        .IsRequired();
                });

            modelBuilder.Entity("VvsIms.Domain.Entities.StockReturn", b =>
                {
                    b.HasOne("VvsIms.Domain.Entities.Stock", "Stock")
                        .WithMany()
                        .HasForeignKey("StockId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Stock");
                });

            modelBuilder.Entity("VvsIms.Domain.Entities.User", b =>
                {
                    b.HasOne("VvsIms.Domain.Entities.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_user_role");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("VvsIms.Domain.Entities.Inventory", b =>
                {
                    b.Navigation("InventoryItems");
                });

            modelBuilder.Entity("VvsIms.Domain.Entities.Role", b =>
                {
                    b.Navigation("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
